spring.application.name=caseflow-ops

spring.datasource.url=jdbc:postgresql://localhost:5432/caseflow_ops
spring.datasource.username=caseflow_user
spring.datasource.password=caseflow_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.docker.compose.enabled=false

server.port=8080